# Generated by Django 4.1.5 on 2023-01-20 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='desc',
            new_name='desccription',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='img',
            new_name='images',
        ),
    ]
