# Generated by Django 4.1.5 on 2023-01-20 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_rename_desc_people_desccription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='desccription',
            new_name='description',
        ),
    ]
