# Generated by Django 4.1.5 on 2023-01-20 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_rename_desccription_people_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='name',
            new_name='names',
        ),
    ]
